apiVersion: batch/v1
kind: Job
metadata:
  name: test-job
  labels:
    app: service1
spec:
  template:
    metadata:
      name: test-job
    spec:
      containers:
      - name: test-container
        image: gcr.io/google_containers/busybox
        command: [ "/bin/sh", "-c", "sleep 360; env"]
      restartPolicy: Never
