apiVersion: v1
kind: Pod
metadata:
  name: eventually-alive-service-pod
  labels:
    app: service1
spec:
  containers:
  - command: ["/bin/sh"]
    args:
    - -c
    - echo ok > /tmp/health; sleep 10 ; rm /tmp/health ; sleep 120 ; echo ok > /tmp/health ; sleep 600
    image: gcr.io/google_containers/busybox
    readinessProbe:
      exec:
        command:
        - /bin/cat
        - /tmp/health
    name: test-container
