apiVersion: v1
kind: Pod
spec:
  containers:
    - image: "nebril/centos-binary-mariadb"
      name: mariadb
      volumeMounts:
        - mountPath: /var/lib/kolla/config_files
          name: mariadb-config
        - mountPath: /var/lib/mysql
          name: mariadb-persistent-storage
        - mountPath: /var/log/kolla/
          name: kolla-logs
      env:
        - name: KOLLA_KUBERNETES
          value: ""
        - name: KOLLA_CONFIG_STRATEGY
          value: COPY_ALWAYS
      ports:
        - containerPort: 3306
          name: mariadb
  volumes:
    - name: mariadb-config
      configMap:
        name: mariadb-configmap
    - name: mariadb-persistent-storage
      persistentVolumeClaim:
        claimName: mariadb
    - name: kolla-logs
      emptyDir: {}
metadata:
  name: mariadb
  labels:
    service: mariadb
