apiVersion: batch/v1
kind: Job
metadata:
  name: test-job3
spec:
  template:
    metadata:
      name: test-job3
    spec:
      containers:
      - name: test-container
        image: gcr.io/google_containers/busybox
        command: [ "/bin/sh", "-c", "sleep 20; env"]
      restartPolicy: Never
