apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: test-petset
spec:
  serviceName: "petset"
  replicas: 2
  template:
    metadata:
      labels:
        app: nginx
      annotations:
        pod.alpha.kubernetes.io/initialized: "true"
    spec:
      terminationGracePeriodSeconds: 0
      containers:
      - command: ["/bin/sh"]
        args:
        - -c
        - sleep 30; echo ok > /tmp/health; sleep 600
        image: gcr.io/google_containers/busybox
        readinessProbe:
          exec:
            command:
            - /bin/cat
            - /tmp/health
        name: test-container
      - command: ["/bin/sh"]
        args:
        - -c
        - sleep 30; echo ok > /tmp/health; sleep 600
        image: gcr.io/google_containers/busybox
        readinessProbe:
          exec:
            command:
            - /bin/cat
            - /tmp/health
        name: test-container2
