apiVersion: v1
kind: Pod
metadata:
  name: eventually-alive-pod7
spec:
  containers:
  - command: ["/bin/sh"]
    args:
    - -c
    - sleep 40; echo ok > /tmp/health; sleep 600
    image: gcr.io/google_containers/busybox
    readinessProbe:
      exec:
        command:
        - /bin/cat
        - /tmp/health
    name: test-container
