apiVersion: batch/v1
kind: Job
metadata:
  name: pi
spec:
  template:
    metadata:
      name: pi
    spec:
      containers:
      - name: pi
        image: perl
        command: ["/bin/bash", "-c", "perl -Mbignum=bpi -wle 'print bpi(5000)' > /pi/pi"]
        volumeMounts:
        - mountPath: /pi
          name: pivol
      restartPolicy: Never
      volumes:
      - name: pivol
        hostPath:
          path: /data
