#!/bin/bash
echo "=> Building the binary"

docker run --privileged -w /go/src/github.com/Mirantis/k8s-AppController -v $(pwd)/../:/go/src/github.com/Mirantis/k8s-AppController golang:alpine sh -c "echo \"@community http://dl-cdn.alpinelinux.org/alpine/edge/community\" >> /etc/apk/repositories; apk --no-cache add git glide@community; glide install --strip-vendor; go build -o kubeac; mkdir -p /opt/kubeac"

