apiVersion: appcontroller.k8s/v1alpha1
kind: Flow
metadata:
  name: etcd-scale

exported: true
construction:
  flow: etcd-scale
destruction:
  flow: cleanup

replicaSpace: etcd-$clusterName-node

parameters:
  clusterName:
    description: etcd cluster name
    default: etcd
