apiVersion: v1
kind: Service
metadata:
  labels:
    app: etcd
    cluster: $clusterName
    serviceRole: cluster
  name: $clusterName-client
spec:
  type: NodePort
  ports:
  - name: etcd-client-port
    port: 2379
    protocol: TCP
    targetPort: 2379
  selector:
    app: etcd
    cluster: $clusterName

